/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppDemoRouteImport } from './routes/_authenticated/app.demo'
import { Route as AuthenticatedAppNewClassRouteImport } from './routes/_authenticated/app.new-class'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes.index'
import { Route as AuthenticatedClassesNewRouteImport } from './routes/_authenticated/classes.new'
import { Route as AuthenticatedClassesIdIndexRouteImport } from './routes/_authenticated/classes.$id.index'
import { Route as AuthenticatedClassesIdRecordRouteImport } from './routes/_authenticated/classes.$id.record'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDemoRoute = AuthenticatedAppDemoRouteImport.update({
  id: '/app/demo',
  path: '/app/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppNewClassRoute =
  AuthenticatedAppNewClassRouteImport.update({
    id: '/app/new-class',
    path: '/app/new-class',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesNewRoute = AuthenticatedClassesNewRouteImport.update({
  id: '/classes/new',
  path: '/classes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesIdIndexRoute =
  AuthenticatedClassesIdIndexRouteImport.update({
    id: '/classes/$id/',
    path: '/classes/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesIdRecordRoute =
  AuthenticatedClassesIdRecordRouteImport.update({
    id: '/classes/$id/record',
    path: '/classes/$id/record',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/app/demo': typeof AuthenticatedAppDemoRoute
  '/app/new-class': typeof AuthenticatedAppNewClassRoute
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/classes/$id/record': typeof AuthenticatedClassesIdRecordRoute
  '/classes/$id/': typeof AuthenticatedClassesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/app/demo': typeof AuthenticatedAppDemoRoute
  '/app/new-class': typeof AuthenticatedAppNewClassRoute
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/classes/$id/record': typeof AuthenticatedClassesIdRecordRoute
  '/classes/$id': typeof AuthenticatedClassesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/app/demo': typeof AuthenticatedAppDemoRoute
  '/_authenticated/app/new-class': typeof AuthenticatedAppNewClassRoute
  '/_authenticated/classes/new': typeof AuthenticatedClassesNewRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/classes/$id/record': typeof AuthenticatedClassesIdRecordRoute
  '/_authenticated/classes/$id/': typeof AuthenticatedClassesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/app/demo'
    | '/app/new-class'
    | '/classes/new'
    | '/app/'
    | '/classes/'
    | '/classes/$id/record'
    | '/classes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/app/demo'
    | '/app/new-class'
    | '/classes/new'
    | '/app'
    | '/classes'
    | '/classes/$id/record'
    | '/classes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/app/demo'
    | '/_authenticated/app/new-class'
    | '/_authenticated/classes/new'
    | '/_authenticated/app/'
    | '/_authenticated/classes/'
    | '/_authenticated/classes/$id/record'
    | '/_authenticated/classes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/demo': {
      id: '/_authenticated/app/demo'
      path: '/app/demo'
      fullPath: '/app/demo'
      preLoaderRoute: typeof AuthenticatedAppDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/new-class': {
      id: '/_authenticated/app/new-class'
      path: '/app/new-class'
      fullPath: '/app/new-class'
      preLoaderRoute: typeof AuthenticatedAppNewClassRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/new': {
      id: '/_authenticated/classes/new'
      path: '/classes/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof AuthenticatedClassesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$id/': {
      id: '/_authenticated/classes/$id/'
      path: '/classes/$id'
      fullPath: '/classes/$id/'
      preLoaderRoute: typeof AuthenticatedClassesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$id/record': {
      id: '/_authenticated/classes/$id/record'
      path: '/classes/$id/record'
      fullPath: '/classes/$id/record'
      preLoaderRoute: typeof AuthenticatedClassesIdRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAppDemoRoute: typeof AuthenticatedAppDemoRoute
  AuthenticatedAppNewClassRoute: typeof AuthenticatedAppNewClassRoute
  AuthenticatedClassesNewRoute: typeof AuthenticatedClassesNewRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedClassesIdRecordRoute: typeof AuthenticatedClassesIdRecordRoute
  AuthenticatedClassesIdIndexRoute: typeof AuthenticatedClassesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAppDemoRoute: AuthenticatedAppDemoRoute,
  AuthenticatedAppNewClassRoute: AuthenticatedAppNewClassRoute,
  AuthenticatedClassesNewRoute: AuthenticatedClassesNewRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedClassesIdRecordRoute: AuthenticatedClassesIdRecordRoute,
  AuthenticatedClassesIdIndexRoute: AuthenticatedClassesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
